### PR TITLE
GitHub Actions Implementation

### PR DESCRIPTION
**Pull request by Stoops-ML**

### CODE REVIEW

**Comment by Stoops-ML** [comment]
CircleCI action(?) needs to be removed from the repo.

Also, GitHub actions fails on Code Coverage: `Error: Codecov token not found. Please provide Codecov token with -t flag.`

A v1.0.0 tag needs to be added too.

**Comment by astrojuanlu** [comment]
Removed CircleCI checks as required.

I don't see the GHA ones coming up here in the PR though.

About Codecov, I can have a look at it. It's been a while since I last used the service, it became somewhat flaky.

**Comment by Stoops-ML** [comment]
I’m happy to implement an alternative to Codecov if you’d like. 

I need to make another commit to trigger the actions on pull request (currently they’re only triggered on pushes).

**Comment by Stoops-ML** [comment]
GitHub actions are now running!

**Comment by Stoops-ML** [comment]
GitHub actions are now running! CircleCI still running though.

**Comment by astrojuanlu** [comment]
Stopped CircleCI builds.

Added `CODECOV_TOKEN` to the Actions secrets, Codecov now suggests

```
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v4.0.1
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
```

**Comment by Stoops-ML** [comment]
> Added `CODECOV_TOKEN` to the Actions secrets, Codecov now suggests
> 
> ```
> - name: Upload coverage reports to Codecov
>   uses: codecov/codecov-action@v4.0.1
>   with:
>     token: ${{ secrets.CODECOV_TOKEN }}
> ```

That action is already in the workflow file (see [here](https://github.com/poliastro/czml3/blob/e48e1d207639750fadf74f7c814ca4ed1bb14dd1/.github/workflows/workflow.yml#L72)).

I will make another commit to update the Codecov action from v4 to v4.0.1.

**Comment by Stoops-ML** [comment]
CircleCI has indeed stopped. However, Codecov is still throwing the error `Codecov token not found`. See [here](https://github.com/poliastro/czml3/blob/e48e1d207639750fadf74f7c814ca4ed1bb14dd1/.github/workflows/workflow.yml#L72) for the Codecov configuration in the GitHub actions workflow file.

Did you follow the Codecov instructions [here](https://docs.codecov.com/docs/adding-the-codecov-token) for adding the token?

If a quick work-around is desired, I can disable the `fail_ci_if_error` parameter for Codecov.

**Comment by astrojuanlu** [comment]
> Did you follow the Codecov instructions [here](https://docs.codecov.com/docs/adding-the-codecov-token) for adding the token?

I thought I had, but I had added it to my fork 🥲 Added it now, please try again.

**Review by astrojuanlu — DISMISSED** [review]
Merging if the CI passes

**Comment by astrojuanlu** [comment]
Secrets "are not passed to workflows that are triggered by a pull request from a fork."

image

Also, from Codecov instructions:

> Keep in mind that secrets are not available to forks of repositories.

https://github.com/codecov/codecov-action?tab=readme-ov-file#usage

So I guess everything is working as expected now.

**Comment by astrojuanlu** [comment]
I'm proceeding with the merge to see if the `main` branch is able to upload the Codecov report. But we'll have to figure out what to do in this case.

**Comment by astrojuanlu** [comment]
> Error: No coverage reports found. Please make sure you're generating reports successfully.
> Error: Codecov:
>                         Failed to properly upload report: The process '/home/runner/work/_actions/codecov/codecov-action/v4.5.0/dist/codecov' failed with exit code 1

Nope, broken

**Comment by astrojuanlu** [comment]
@Stoops-ML you have write access now, try creating a branch in this repo so that the coverage action works.

**Comment by Stoops-ML** [comment]
> > Error: No coverage reports found. Please make sure you're generating reports successfully.
> > Error: Codecov:
> > Failed to properly upload report: The process '/home/runner/work/_actions/codecov/codecov-action/v4.5.0/dist/codecov' failed with exit code 1
> 
> Nope, broken

From the error message it seems like the token was found, but the coverage reports weren't generated. I don't understand this behaviour if secrets aren't passed to workflows of forks of repos.

I'll make a PR, which will produce the coverage reports, from my fork to test this behaviour.

**Pull request merged**
