### PR TITLE
Add Box and EyeOffset properties

### PR DESCRIPTION
**Pull request by Sedictious**

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Could you add a test for `EyeOffset` please? :)

**Comment by astrojuanlu** [comment]
This will require a rebase to pass the Python 3.8 check

**Comment by Sedictious** [comment]
@Juanlu001 *I think* this is ready to merge now

**Review by astrojuanlu — APPROVED** [review]

**Comment by astrojuanlu** [comment]
@Sedictious thanks a lot!

**Pull request merged**
