### PR TITLE
core.py - added support for description

### PR DESCRIPTION
**Pull request by idanmiara**

### CODE REVIEW

**Review by astrojuanlu — APPROVED** [review]

**Comment by astrojuanlu** [comment]
Sorry for the delay, and thanks for this PR!

**Comment by idanmiara** [comment]
Thanks!

**Comment by idanmiara** [comment]
Would you please update the pypi package?

**Comment by idanmiara** [comment]
Hi,
Would you please update the pypi package?
Thanks.

**Comment by astrojuanlu** [comment]
Apologies for the looooooong wait, it's over!

**Pull request merged**
