### PR TITLE
Add holes attribute to polygon

### PR DESCRIPTION
**Pull request by Stoops-ML**
- Add holes attribute to polygon
- Add PositionListOfLists property
- Test added for above changes

### CODE REVIEW

**Comment by Stoops-ML** [comment]
@astrojuanlu any idea why the circleci quality check is failing?

**Comment by astrojuanlu** [comment]
Ugh, direct invokations of `setup.py` on the command line are deprecated and possibly broken... 

```
python setup.py check
```

Looks like we'll need to get the CI green first (worth doing so in a separate PR)

**Comment by Stoops-ML** [comment]
This would close https://github.com/poliastro/czml3/issues/96

**Review by astrojuanlu — DISMISSED** [review]
LGTM!

**Comment by astrojuanlu** [comment]
Will require editing some merge conflicts

**Review by astrojuanlu — APPROVED** [review]

**Pull request merged**
