### PR TITLE
Add setuptools to install_requires

### PR DESCRIPTION
**Pull request by Stoops-ML**
This allows for passing the CI quality check

### CODE REVIEW

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
I'd rather move away from depending directly on `setuptools`, see for example https://github.com/astrojuanlu/copier-pylib for (my) modern take on how to structure CI, quality checks, etc

**Comment by Stoops-ML** [comment]
Seems like the problem was the CI quality check using the python:3 docker image, which I've now swapped out for python:3.9.

I'll submit an additional PR to add CI checks on pythons 3.10, 3.11 and 3.12.

**Review by astrojuanlu — APPROVED** [review]
LGTM!

**Comment by astrojuanlu** [comment]
Thank you @Stoops-ML !

**Pull request merged**
