### PR TITLE
add ViewFrom, fixup nit

### PR DESCRIPTION
**Pull request by mhaberler**

### CODE REVIEW

**Comment by mhaberler** [comment]
not sure I should run 'tox -e reformat' on this and commit it?

this is the changes it would cause: https://github.com/mhaberler/czml3/commit/2bb86cf3fd2f470ff5b01e717e1c8abc3f67fd8a

**Comment by mhaberler** [comment]
halleluja. long live the learning curve!

**Comment by astrojuanlu** [comment]
Glad to see you got `tox` running @mhaberler , and thanks for this PR! Reviewing it right now :eyes:

**Review by astrojuanlu — APPROVED** [review]

**Comment by astrojuanlu** [comment]
Merged! :rocket:

**Comment by mhaberler** [comment]
had to move to Python 3.8 from 3.9 on OSX to get everything in sync. Thanks!

**Pull request merged**
