### PR TITLE
Label: add pixelOffset property, Polyline: support PolylineDashMaterial property

### PR DESCRIPTION
**Pull request by mhaberler**
whitespace fixed, hopefully

### CODE REVIEW

**Comment by astrojuanlu** [comment]
I made a commit to your branch to try to skip an annoying check of the Continuous Integration.

**Comment by mhaberler** [comment]
thanks for the patience! still a bit lost. I'll get there.

**Review by astrojuanlu — APPROVED** [review]
Ready! :rocket:

**Comment by astrojuanlu** [comment]
Thanks a lot for your contribution @mhaberler! I had a release pending from a long time ago. Will try to do one in the coming days.

**Comment by astrojuanlu** [comment]
czml3 0.5.4 is released 🎉

**Pull request merged**
