### PR TITLE
attr -> pydantic

### PR DESCRIPTION
**Pull request by Stoops-ML**
Replace attrs with pydantic.

- Type checking of every argument of every class
- Simplifies dumping to json string
- Bumps version to 2.0.0 as there are breaking changes
- Supports Python 3.11 upwards due to using type hints Self and StrEnum. StrEnum is very useful as all classes in enums.py can be used with auto() to return the exact member. Self isn't critical and less clean alternatives can be found for replacing StrEnum in order to support Pythons <3.11.
- Tests have been modified minimally to account for small changes in output (e.g. spaces in how pydantic performs the model dump). All tests pass in this current PR for Pythons 3.11+.

@astrojuanlu Let me know your thoughts.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Oh I love this idea! I think it makes a ton of sense. Cannot look into the code just yet but ping me again when the CI is green

**Comment by Stoops-ML** [comment]
What's your decision on typing? If we're using Self and StrEnum then we're limited to Python 3.11+ (see my original post).

**Comment by astrojuanlu** [comment]
>  If we're using Self and StrEnum then we're limited to Python 3.11+ 

Aren't there backports in `typing_extensions` or similar?

**Comment by Stoops-ML** [comment]
Python 3.7 support has been dropped as Pydantic>=2.10.0 doesn't support it.

@astrojuanlu

**Comment by astrojuanlu** [comment]
Good for me, 3.7 is EOL anyway. So is 3.8, by the way. Let's drop both.

I see you replaced `|` with `Union` everywhere, is that necessary?

**Comment by Stoops-ML** [comment]
Python 3.8 dropped.

pydantic doesn't work with `|` on Python 3.9 even with `from __future__ import annotations` specified. Someone noted the problem on SO [here](https://stackoverflow.com/questions/76579085/python-3-9-use-or-operator-for-union-types). 

Want to drop Python 3.9 or implement `Union`?

**Comment by astrojuanlu** [comment]
Hm interesting. Well, let's drop Python 3.9 then!

**Comment by Stoops-ML** [comment]
All checks passed!

**Review by astrojuanlu — APPROVED** [review]
LGTM!

**Pull request merged**
